name: build-edr-deno

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-14
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        if: matrix.os == 'macos-14'
        run: cargo build --target ${{ matrix.target }} --release -p edr_deno

      - uses: actions-rs/cargo@v1
        if: matrix.os != 'macos-14'
        with:
          use-cross: true
          command: build
          args: --target ${{ matrix.target }} --release -p edr_deno

      - name: Place artifact
        run: |
          for f in target/${{ matrix.target }}/release/libedr_deno*.{so,dylib,dll}; do
            [ -e "$f" ] && cp "$f" "crates/edr_deno/edr_deno.${{ matrix.target }}.${f##*.}" && break
          done

      - uses: actions/upload-artifact@v4
        with:
          name: prebuild-${{ matrix.target }}
          path: crates/edr_deno/edr_deno.${{ matrix.target }}.*
          retention-days: 1

  pack:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: prebuild-*
          path: crates/edr_deno
          merge-multiple: true

      - name: Package artifacts
        run: |
          crate_version=$(grep '^version' crates/edr_deno/Cargo.toml | head -n1 | cut -d '"' -f2)
          tar czf nomicfoundation-edr-deno-$crate_version.tgz crates/edr_deno/README.md crates/edr_deno/bindings/bindings.ts crates/edr_deno/edr_deno.*

      - uses: actions/upload-artifact@v4
        with:
          name: nomicfoundation-edr-deno
          path: nomicfoundation-edr-deno-*.tgz
